"use client"

import { useEffect, useRef } from "react"
import { motion } from "framer-motion"
import { Button } from "@/components/ui/button"
import { ArrowRight, Sparkles, Zap } from "lucide-react"
import Link from "next/link"
import gsap from "gsap"

export function HeroSection() {
  const titleRef = useRef<HTMLHeadingElement>(null)
  const subtitleRef = useRef<HTMLParagraphElement>(null)
  const floatingRef1 = useRef<HTMLDivElement>(null)
  const floatingRef2 = useRef<HTMLDivElement>(null)
  const floatingRef3 = useRef<HTMLDivElement>(null)

  useEffect(() => {
    // GSAP animations for title
    if (titleRef.current) {
      gsap.from(titleRef.current.children, {
        opacity: 0,
        y: 50,
        duration: 0.8,
        stagger: 0.2,
        ease: "power3.out",
      })
    }

    if (subtitleRef.current) {
      gsap.from(subtitleRef.current, {
        opacity: 0,
        y: 30,
        duration: 0.8,
        delay: 0.6,
        ease: "power3.out",
      })
    }

    // Floating animations
    const floatingElements = [floatingRef1.current, floatingRef2.current, floatingRef3.current]
    floatingElements.forEach((el, index) => {
      if (el) {
        gsap.to(el, {
          y: "+=30",
          duration: 2 + index * 0.5,
          repeat: -1,
          yoyo: true,
          ease: "power1.inOut",
        })
      }
    })
  }, [])

  return (
    <section className="relative min-h-screen flex items-center justify-center overflow-hidden pt-16 md:pt-20">
      <div className="absolute inset-0 z-0">
        <img src="/hero.png" alt="Hero background" className="w-full h-full object-cover" />
        <div className="absolute inset-0 bg-gradient-to-b from-gray-100 via-gray-300 to-gray-400 opacity-50" />
      </div>

      <div
        ref={floatingRef1}
        className="absolute top-20 left-10 md:left-20 w-32 h-32 bg-gradient-to-br from-primary/30 to-secondary/20 rounded-2xl blur-2xl transform rotate-12"
        style={{ transform: "perspective(1000px) rotateX(15deg) rotateY(-15deg)" }}
      />
      <div
        ref={floatingRef2}
        className="absolute top-40 right-10 md:right-20 w-40 h-40 bg-gradient-to-br from-secondary/30 to-accent/20 rounded-3xl blur-2xl transform -rotate-12"
        style={{ transform: "perspective(1000px) rotateX(-15deg) rotateY(15deg)" }}
      />
      <div
        ref={floatingRef3}
        className="absolute bottom-20 left-1/3 w-36 h-36 bg-gradient-to-br from-accent/30 to-primary/20 rounded-2xl blur-2xl transform rotate-45"
        style={{ transform: "perspective(1000px) rotateX(10deg) rotateZ(45deg)" }}
      />

      <div className="container mx-auto px-4 lg:px-8 relative z-10">
        <div className="max-w-4xl mx-auto text-center">
          {/* Badge */}
          <motion.div
            initial={{ opacity: 0, scale: 0.8 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.5 }}
            className="inline-flex items-center gap-2 px-4 py-2 bg-primary/20 backdrop-blur-md border border-primary/30 rounded-full text-sm font-medium text-primary mb-8"
          >
            <Sparkles className="w-4 h-4" />
            <span>AI-Powered Fitness Coaching</span>
          </motion.div>

          {/* Main heading */}
          <h1 ref={titleRef} className="text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-bold mb-6 leading-tight">
            <span className="block text-balance text-gray-700 drop-shadow-2xl">Transform Your Body</span>
            <span className="block bg-gradient-to-r from-primary via-secondary to-accent bg-clip-text text-transparent text-balance drop-shadow-lg">
              With AI-Powered Workouts
            </span>
          </h1>

          {/* Subtitle */}
          <p
            ref={subtitleRef}
            className="text-lg md:text-xl text-gray-800 mb-8 max-w-2xl mx-auto text-balance drop-shadow-lg"
          >
            Get personalized workout plans generated by advanced AI, tailored to your fitness level, goals, and
            available equipment. Start your transformation today.
          </p>

          {/* CTA Buttons */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 1 }}
            className="flex flex-col sm:flex-row items-center justify-center gap-4"
          >
            <Button size="lg" className="group w-full sm:w-auto shadow-2xl shadow-primary/50" asChild>
              <Link href="/auth/sign-up">
                Generate Your Plan
                <ArrowRight className="ml-2 w-4 h-4 group-hover:translate-x-1 transition-transform" />
              </Link>
            </Button>
            <Button
              size="lg"
              variant="outline"
              className="w-full sm:w-auto bg-white/10 backdrop-blur-md border-white/30 text-gray-700 hover:bg-white/20"
              asChild
            >
              <Link href="#how-it-works">See How It Works</Link>
            </Button>
          </motion.div>

          {/* Social proof */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.5, delay: 1.2 }}
            className="flex flex-col sm:flex-row items-center justify-center gap-6 mt-12 text-sm text-gray-300"
          >
            <div className="flex items-center gap-2">
              <Zap className="w-4 h-4 text-primary" />
              <span className="text-gray-800">10,000+ Workouts Generated</span>
            </div>
            <div className="hidden sm:block w-1 h-1 bg-gray-400 rounded-full" />
            <div className="flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-secondary" />
              <span className="text-gray-800">4.9/5 Average Rating</span>
            </div>
          </motion.div>
        </div>
      </div>

      {/* Bottom gradient */}
      <div className="absolute bottom-0 left-0 right-0 h-32 bg-gradient-to-t from-background to-transparent z-[5]" />
    </section>
  )
}
